// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apdgrnwleckfovayplqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZGdybndsZWNrZm92YXlwbHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njg1NzYsImV4cCI6MjA2NTA0NDU3Nn0.90JE7bQxXkAuvUiAgG-Kx-aeBtjpD0jPaV0qoAFyJtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);